package com.pilldetectionapp.pilloid;
import android.content.Intent;
import android.net.Uri;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.TextView;

import androidx.appcompat.app.AppCompatActivity;

import com.bumptech.glide.Glide;
import com.firebase.ui.auth.AuthUI;
import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.auth.FirebaseUser;

import java.util.Arrays;

public class ActivityChoicePage extends AppCompatActivity {

    private Button run_button;
    private TextView name_view;
    private ImageView profile_image;
    private static final int RC_SIGN_IN = 123;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        // We display the layout of the activity
        setContentView(R.layout.activity_choice_page);
        // initialisation of the profile image
        profile_image = (ImageView)findViewById(R.id.ProfileView);
        Get_and_ShowProfileImage();


        // Change the text with the name of the user
        FirebaseUser user = FirebaseAuth.getInstance().getCurrentUser();
        if (user != null) {
            // We get the name of the user
            String name = user.getDisplayName();
            name_view = (TextView) findViewById(R.id.NameView);
            name_view.setText("Welcome " + name);

        } else {
            // We begin with the authentication
            startSignInActivity();

        }

        // set button
        run_button=(Button)findViewById(R.id.RunButton);
        run_button.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                // WHen the user click on the the run_button we launch the detection activity
                Intent intent = new Intent(ActivityChoicePage.this, CameraActivity.class);
                startActivity(intent);
            }
        });

    }

    // This method allow to launch the signInActivity generated by Firebase
    private void startSignInActivity(){
        startActivityForResult(
                AuthUI.getInstance()
                        .createSignInIntentBuilder()
                        .setTheme(R.style.LoginTheme)
                        // We have just allow to register with Email
                        .setAvailableProviders(
                                Arrays.asList(new AuthUI.IdpConfig.EmailBuilder().build()))
                        .setIsSmartLockEnabled(false, true)
                        .build(),
                RC_SIGN_IN);

    }

    // We check the the result of the previous method
    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        // check if the request code is same as what is passed  here it is 2
        if (requestCode == RC_SIGN_IN) {
            // The user is now register so we refresh the activity
            this.recreate();
        }
    }

    public void ChangeProfileImage(View view) {
            Intent intent = new Intent(ActivityChoicePage.this,TakePhotoActivity.class);
            startActivity(intent);
    }

    private void Get_and_ShowProfileImage(){
        FirebaseUser  user = FirebaseAuth.getInstance().getCurrentUser();
        if (user != null ) {
            Uri uri = user.getPhotoUrl();
            if (uri != null) {
                Glide.with(this)
                        .load(uri)
                        .into(profile_image);
            }
        }
    }
}